$(document).ready(function () {
    $("#signup-form").validate({
        rules:{
            fname:{
                required:true,
                minlength:4
            },
            sname:{
                required:true,
                minlength:4
            },
            emailPhone:{
                required:true,
                email:true
            },
            pass1:{
                required:true,
                minlength:6,
            },
            pass2:{
                required:true,
                equalTo:".pass1"
            },
            day:{
                required:true
            },
            month:{
                required:true
            },
            year:{
                required:true
            },
            gender:{
                required:true
            }
        }
    })
})